# Generated by Django 5.0.3 on 2024-05-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_category_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
    ]
