# Generated by Django 5.0.3 on 2024-05-17 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listingComment",
                to="auctions.listing",
            ),
        ),
    ]
